# Generated by Django 3.2.8 on 2021-10-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
