# Generated by Django 3.2.8 on 2021-10-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211025_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
