# Generated by Django 3.2.8 on 2021-11-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
